### ISSUE TITLE
Error in simple example

### ISSUE THREAD

**Issue by lorentzenchr** [aijordan/reliabilitydiag#4]
First of all, thank you for this nice package.

The following code snippet from the documentation
```R
library(reliabilitydiag)

data("precip_Niamey_2016", package = "reliabilitydiag")
X <- precip_Niamey_2016$EMOS
Y <- precip_Niamey_2016$obs
reliabilitydiag(EMOS = X, y = Y)
```
produces the error
```
Error in FUN(newX[, i], ...) : unused argument (simplify = FALSE)
```
The error disappears with `reliabilitydiag(EMOS = X, y = Y, region.level = NA)`.
I have the following system settings:
- R version 4.0.4
- reliabilitydiag verion 0.2.0
- MacO 12

**Comment by aijordan** [comment]
@lorentzenchr, thanks for the report. Apparently, the resampling routine for consistency/confidence regions in reliabilitydiag version 0.2.0 uses a feature introduced in R version 4.1.0

> CHANGES IN R 4.1.0
>
> NEW FEATURES
> - apply() gains a simplify argument to allow disabling of simplification of results.

https://cran.r-project.org/doc/manuals/r-devel/NEWS.html

We should fix the dependency declaration in the DESCRIPTION file. I hope you are not stuck on R version 4.0.4, and an update will resolve your problems.

**Comment by lorentzenchr** [comment]
Thanks for checking. I have access to R 4.1.0.
