### ISSUE TITLE
Error when running reliabilitydiag

### ISSUE THREAD

**Issue by rjordan-hdai** [aijordan/reliabilitydiag#5]
When I try the example you have provided, I get this error:

 library(reliabilitydiag)
> data("precip_Niamey_2016", package = "reliabilitydiag")
> X <- precip_Niamey_2016$EMOS
> Y <- precip_Niamey_2016$obs
> reliabilitydiag(EMOS = X, y = Y)
Error in FUN(newX[, i], ...) : unused argument (simplify = FALSE)

**Comment by aijordan** [comment]
Thanks, @rjordan-hdai

Most likely, this is the same problem as in #4, and updating to R version 4.1.0 or newer should resolve the issue. If you cannot update R, you could use `region.method = NA` or one of the asymptotic methods to calculate the consistency/confidence regions.

We will address this bug, either by correcting the dependency in the DESCRIPTION file, or by improving backwards compatibility.

**Comment by rjordan-hdai** [comment]
Thanks! Since the data sets I'm dealing with are quite large, the continuous_asymptotics region.method is probably sufficient for my purposes. But it would be good to try the resampling method.

**Comment by aijordan** [comment]
Backwards compatibility has been improved. The current development version (0.2.0.9000) is tested to work with R >= 3.5.
